"""
Author: Susheel Bhanu BUSI
Affiliation: Molecular Ecology group, UKCEH
Date: [2023-10-15]
Run: snakemake -s workflow/Snakefile --configfile config/config.yaml --use-conda --cores 4 -rp
Latest modification:
Purpose: Running metagenomic analyses for the DECODE project
"""


##############################
# MODULES
import os
import re
import glob
import pandas as pd

# importing specific scripts for parsing etc.
# from scripts.utils import find_fast5, assembler_pairs


##############################
# CONFIG
include:
    "rules/init.smk"


##############################
# TARGETS & RULES
# List of (main) targets to be created
TARGETS = []

# Include rules and add targets based on the config file
# include:
#     "rules/setup.smk"
include:
    "rules/databases.smk"

# PROFILE
if "profiles" in config["steps"]:
    include:
        "rules/preprocessing.smk"
    include:
        "rules/kraken2.smk"
    include:
        "rules/metaphlan.smk"
    include:
        "rules/singlem.smk"
    TARGETS += [
        "status/preprocessing.done",
        "status/taxonomy.done",
        "status/metaphlan.done",
        "status/singlem.done"
    ]

# ASSEMBLY
if "assembly" in config["steps"]:
    include:
        "rules/assembly.smk"
    include:
        "rules/kaiju.smk"
    TARGETS += [
        "status/assembly.done",
        "status/kaiju.done"
    ]

# MAGS
if "mags" in config["steps"]:
    include:
        "rules/binning.smk"
    TARGETS += [
        "status/binning.done"
    ]

# ANALYSES
if "analysis" in config["steps"]:
    include:
        "rules/annotation.smk"
    include:
        "rules/card.smk"
    include:
        "rules/eggnog.smk"
    TARGETS += [
        "status/annotation.done",
        "status/card.done",
        "status/eggnog.done"
    ]


# No targets
if len(TARGETS) == 0:
    raise Exception('You are not serious. Nothing to be done? Really?')

rule all:
    input:
        TARGETS

